### ISSUE TITLE
Requirements - error on windows

### ISSUE THREAD

**Issue by Squattydent** [ritiek/scribd-downloader#13]
**requirements**

1. BeautifulSoup4
2. requests
3. img2pdf

```
D:\scribd>python setup.py install
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    import scribdl
  File "D:\scribd\scribdl\__init__.py", line 3, in <module>
    from .scribdl import *
  File "D:\scribd\scribdl\scribdl.py", line 3, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'
```

Fixed : 
1. D:\scribd>pip install beautifulsoup4
2. D:\scribd>pip install requests
3. D:\scribd>pip install img2pdf
4. D:\scribd>python setup.py install

**Comment by ritiek** [comment]
Thanks for this! I've just added the command `$ pip install -r requirements.txt` to README that installs all required dependencies (da48df18b977c11fa885e73f139578bedba07f77).
