### ISSUE TITLE
Download fail

### ISSUE THREAD

**Issue by Sphinxs** [ritiek/scribd-downloader#20]
The script `scribdl -i link` download fifteen pages and then stop.

**Comment by ritiek** [comment]
Can you provide the link to the document you're trying to download? I'll take a look.

**Comment by Sphinxs** [comment]
[Interacao Humano-Computador - Benyon](scribd.com/document/376617508/Livro-Interacao-Humano-Computador-Benyon-pdf)

**Comment by ritiek** [comment]
It says `x of 15` which probably means that either rest of the pages (later than page 15) are not being exposed to us or document on scribd itself has only 15 pages. In either case, there isn't anything much we could do, sorry.

**Comment by Sphinxs** [comment]
It's fine, I understand the complexity involved in this process of scraper in sites like Scribd. Thanks ( :
