### ISSUE TITLE
No able to download document

### ISSUE THREAD

**Issue by jackaw** [ritiek/scribd-downloader#21]
Hello!

I'm trying to download a book but the following error appears:

Traceback (most recent call last):
  File "/home/user/.local/bin/scribdl", line 11, in <module>
    sys.exit(command_line())
  File "/home/user/.local/lib/python2.7/site-packages/scribdl/scribdl.py", line 242, in command_line
    book.get_book()
  File "/home/user/.local/lib/python2.7/site-packages/scribdl/scribdl.py", line 205, in get_book
    except json.decoder.JSONDecodeError:
AttributeError: 'module' object has no attribute 'JSONDecodeError'

Here the command i use:  
`scribdl -i https://pt.scribd.com/read/371974195/Nicholas-Carr-A-Geracao-Superficial-O-Que-a-Internet-Esta-Fazendo-Com-Nossos-Cerebros-1#`

**Comment by ritiek** [comment]
The tool is having some trouble in detecting whether the input URL is a book or a document. I'll take a look soon.

For now you can use this command instead to download the text:
```
$ scribdl https://scribd.com/read/371974195/Nicholas-Carr-A-Geracao-Superficial-O-Que-a-Internet-Esta-Fazendo-Com-Nossos-Cerebros-1#
```

**Comment by ritiek** [comment]
#25 should correctly detect documents and books.
