### ISSUE TITLE
Not working on some links

### ISSUE THREAD

**Issue by blueberrysnapple** [ritiek/scribd-downloader#3]
Hello, 

I'm not sure why this won't work here but all photo's are blank when viewed. 

https://www.scribd.com/document/31698781/Constitution-of-the-Mexican-Mafia-in-Texas

**Comment by ritiek** [comment]
Thanks for reporting this, I'll investigate.

**Comment by ritiek** [comment]
3cd422ad8f9b37ee032e44d14c796a0d01bf2aa9 should fix this. Upgrade to v0.1.5 with:
```
pip install scribd-downloader -U
```
Ping me if still faulty.

**Comment by blueberrysnapple** [comment]
Thanks a bunch. Working great now!
