### ISSUE TITLE
problem in ubuntu

### ISSUE THREAD

**Issue by ViniciusBRodrigues** [ritiek/scribd-downloader#36]
Hi there, very thanks for you work.

I installed scribd-downloader but the system doesn't find it:

`pip3 install scribd-downloader
Collecting scribd-downloader
  Downloading https://files.pythonhosted.org/packages/95/1d/629349fd80cb17e20ea7f997175fd5c7efbd003f0bead685274893c4afde/scribd_downloader-1.1.1-py3-none-any.whl
Collecting img2pdf (from scribd-downloader)
  Using cached https://files.pythonhosted.org/packages/56/1e/675f153521e727b7e30da26bb4a76b9730711cbb664b2338e349aef1ce4c/img2pdf-0.3.2.tar.gz
Collecting md2pdf (from scribd-downloader)
  Using cached https://files.pythonhosted.org/packages/a4/f4/94df8506f6164f0704eb71713f5db1f6017d987f9339d3a9a4f04ed47094/md2pdf-0.4-py2.py3-none-any.whl
Collecting BeautifulSoup4 (from scribd-downloader)
  Downloading https://files.pythonhosted.org/packages/3f/ef/40271f62429deec36f2d040283e722856abcfd34bac063435a2213b77bef/beautifulsoup4-4.7.0-py3-none-any.whl (92kB)
    100% |████████████████████████████████| 102kB 669kB/s 
Collecting requests (from scribd-downloader)
  Using cached https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl
Collecting Pillow (from img2pdf->scribd-downloader)
  Using cached https://files.pythonhosted.org/packages/85/5e/e91792f198bbc5a0d7d3055ad552bc4062942d27eaf75c3e2783cf64eae5/Pillow-5.4.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting docopt (from md2pdf->scribd-downloader)
  Using cached https://files.pythonhosted.org/packages/a2/55/8f8cab2afd404cf578136ef2cc5dfb50baa1761b68c9da1fb1e4eed343c9/docopt-0.6.2.tar.gz
Collecting WeasyPrint (from md2pdf->scribd-downloader)
  Using cached https://files.pythonhosted.org/packages/ec/0e/0d0f72e0832e9566f93d460676d8a34b2131f57424f5985604201a5102bf/WeasyPrint-44-py3-none-any.whl
Collecting markdown2 (from md2pdf->scribd-downloader)
  Downloading https://files.pythonhosted.org/packages/e4/0c/b5375c1c70adbafd0ded0459fa175468559ee5360219070d2f7fb60b2287/markdown2-2.3.7-py2.py3-none-any.whl
Collecting soupsieve>=1.2 (from BeautifulSoup4->scribd-downloader)
  Using cached https://files.pythonhosted.org/packages/ef/06/53edcae4edea76b38a325980dd35aed3b39f9bd0ef27b9d33f2e6dc4c7f6/soupsieve-1.6.2-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->scribd-downloader)
  Downloading https://files.pythonhosted.org/packages/9f/e0/accfc1b56b57e9750eba272e24c4dddeac86852c2bebd1236674d7887e8a/certifi-2018.11.29-py2.py3-none-any.whl (154kB)
    100% |████████████████████████████████| 163kB 1.1MB/s 
Collecting chardet<3.1.0,>=3.0.2 (from requests->scribd-downloader)
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 1.3MB/s 
Collecting urllib3<1.25,>=1.21.1 (from requests->scribd-downloader)
  Downloading https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl (118kB)
    100% |████████████████████████████████| 122kB 1.2MB/s 
Collecting idna<2.9,>=2.5 (from requests->scribd-downloader)
  Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 1.4MB/s 
Collecting CairoSVG>=1.0.20 (from WeasyPrint->md2pdf->scribd-downloader)
  Using cached https://files.pythonhosted.org/packages/5c/57/dadc80948bcb83ea9c0968ccfd5a1a25ace6be0884484526f70dad3c10b9/CairoSVG-2.2.1-py3-none-any.whl
Collecting cssselect2>=0.1 (from WeasyPrint->md2pdf->scribd-downloader)
  Using cached https://files.pythonhosted.org/packages/12/e2/91fcd4cd32545beec6e11628d64d3e20f11b5a95dd1ccf3216fd69f176b7/cssselect2-0.2.1-py2.py3-none-any.whl
Collecting Pyphen>=0.8 (from WeasyPrint->md2pdf->scribd-downloader)
  Using cached https://files.pythonhosted.org/packages/15/82/08a3629dce8d1f3d91db843bb36d4d7db6b6269d5067259613a0d5c8a9db/Pyphen-0.9.5-py2.py3-none-any.whl
Collecting tinycss2>=0.5 (from WeasyPrint->md2pdf->scribd-downloader)
  Using cached https://files.pythonhosted.org/packages/88/95/0ec73db7fc638ec000e662936ffe1a4e1eaa22f2861c8de18b1597c42584/tinycss2-0.6.1-py2.py3-none-any.whl
Collecting html5lib>=0.999999999 (from WeasyPrint->md2pdf->scribd-downloader)
  Using cached https://files.pythonhosted.org/packages/a5/62/bbd2be0e7943ec8504b517e62bab011b4946e1258842bc159e5dfde15b96/html5lib-1.0.1-py2.py3-none-any.whl
Collecting cairocffi>=0.9.0 (from WeasyPrint->md2pdf->scribd-downloader)
Collecting cffi>=0.6 (from WeasyPrint->md2pdf->scribd-downloader)
  Using cached https://files.pythonhosted.org/packages/6d/c0/47db8f624f3e4e2f3f27be03a93379d1ba16a1450a7b1aacfa0366e2c0dd/cffi-1.11.5-cp36-cp36m-manylinux1_x86_64.whl
Collecting defusedxml (from CairoSVG>=1.0.20->WeasyPrint->md2pdf->scribd-downloader)
  Using cached https://files.pythonhosted.org/packages/87/1c/17f3e3935a913dfe2a5ca85fa5ccbef366bfd82eb318b1f75dadbf0affca/defusedxml-0.5.0-py2.py3-none-any.whl
Collecting webencodings>=0.4 (from tinycss2>=0.5->WeasyPrint->md2pdf->scribd-downloader)
  Using cached https://files.pythonhosted.org/packages/f4/24/2a3e3df732393fed8b3ebf2ec078f05546de641fe1b667ee316ec1dcf3b7/webencodings-0.5.1-py2.py3-none-any.whl
Collecting six>=1.9 (from html5lib>=0.999999999->WeasyPrint->md2pdf->scribd-downloader)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting pycparser (from cffi>=0.6->WeasyPrint->md2pdf->scribd-downloader)
Building wheels for collected packages: img2pdf, docopt
  Running setup.py bdist_wheel for img2pdf ... done
  Stored in directory: /home/viniciusbr/.cache/pip/wheels/6a/4a/3b/6a9b51f2db4f31e1b7743fc86b9294438bc0ef15dac12c8787
  Running setup.py bdist_wheel for docopt ... done
  Stored in directory: /home/viniciusbr/.cache/pip/wheels/9b/04/dd/7daf4150b6d9b12949298737de9431a324d4b797ffd63f526e
Successfully built img2pdf docopt
Installing collected packages: Pillow, img2pdf, docopt, defusedxml, webencodings, tinycss2, cssselect2, pycparser, cffi, cairocffi, CairoSVG, Pyphen, six, html5lib, WeasyPrint, markdown2, md2pdf, soupsieve, BeautifulSoup4, certifi, chardet, urllib3, idna, requests, scribd-downloader
Successfully installed BeautifulSoup4-4.7.0 CairoSVG-2.2.1 Pillow-5.4.1 Pyphen-0.9.5 WeasyPrint-44 cairocffi-0.9.0 certifi-2018.11.29 cffi-1.11.5 chardet-3.0.4 cssselect2-0.2.1 defusedxml-0.5.0 docopt-0.6.2 html5lib-1.0.1 idna-2.8 img2pdf-0.3.2 markdown2-2.3.7 md2pdf-0.4 pycparser-2.19 requests-2.21.0 scribd-downloader-1.1.1 six-1.12.0 soupsieve-1.6.2 tinycss2-0.6.1 urllib3-1.24.1 webencodings-0.5.1
`

Then:

`scribdl -p https://pt.scribd.com/document/342843211/Pratica-de-Ensino-de-Biologia-Myriam-Krasilchik-4-Ed
scribdl: comando não encontrado
`

"Command not found"

What could cause this? Thanks in advance. Good job.

**Comment by ritiek** [comment]
You most likely do not have the directory where python bin files get installed to in your `$PATH` environment variable.

Find where the python package got installed:
```
$ find ~/.local/ /usr/ -name scribdl
```
This should give you an output path ending with `bin/scribdl`, so the full path should be something like `[...]/bin/scribdl`.

We need to append this bin directory to the `$PATH` variable.
```
$ echo "export PATH='[...]/bin:$PATH'" >> ~/.bashrc
```

This should be it; try opening a new terminal and `$ scribdl --help`.

**Comment by ViniciusBRodrigues** [comment]
Hi,

`viniciusbr@vbr:~$ find ~/.local/ /usr/ -name scribdl

/home/viniciusbr/.local/bin/scribdl

/home/viniciusbr/.local/lib/python3.6/site-packages/scribdl`

I tried:

`echo "export PATH='[...]/bin:/home/viniciusbr/.local/bin/scribdl'" >> ~/.bashrc`

and

`echo "export PATH='/home/viniciusbr/.local/bin/scribdl'" >> ~/.bashrc`

But still not find it. For sure I'm adding the path in a wrong way. 

Many thanks.

**Comment by ritiek** [comment]
Err.. Yes. You appended the wrong lines to `~/.bashrc`. First you need to remove the wrong lines you added. Edit your `/home/viniciusbr/.bashrc` (files starting with a dot are hidden in Linux, take care of this) and remove the below two lines (and any similar lines at the end if you have run a similar command after you posting the comment):
```
export PATH='[...]/bin:/home/viniciusbr/.local/bin/scribdl'
export PATH='/home/viniciusbr/.local/bin/scribdl'
``` 
from the end of the file.

Exit the file and then run in these commands:
```
source /etc/bash.bashrc
source /etc/profile
source ~/.profile
```

Then edit and add this line at the end of the same file we just edited before (`/home/viniciusbr/.bashrc`):
```
export PATH="$HOME/.local/bin:$PATH"
```
Now close this terminal, open a new one and type `scribdl --help`. It should hopefully work now.

**Comment by ritiek** [comment]
Let me know if there are still any problems.

**Comment by ViniciusBRodrigues** [comment]
Hi again

Now the system is recognizing the installation, but I found the following error:

viniciusbr@vbr:~$ scribdl -p https://pt.scribd.com/document/342843211/Pratica-de-Ensino-de-Biologia-Myriam-Krasilchik-4-Ed
Extracting text to Prática_de_Ensino_de_Biologia_-_Myriam_Krasilchik._4_Ed..md


Converting to Prática_de_Ensino_de_Biologia_-_Myriam_Krasilchik._4_Ed..pdf..
Traceback (most recent call last):
  File "/home/viniciusbr/.local/bin/scribdl", line 11, in <module>
    sys.exit(_command_line())
  File "/home/viniciusbr/.local/lib/python3.6/site-packages/scribdl/command_line.py", line 44, in _command_line
    downloaded_content.to_pdf()
  File "/home/viniciusbr/.local/lib/python3.6/site-packages/scribdl/pdf_converter.py", line 31, in to_pdf
    self._markdown_to_pdf()
  File "/home/viniciusbr/.local/lib/python3.6/site-packages/scribdl/pdf_converter.py", line 39, in _markdown_to_pdf
    base_url=os.getcwd())
  File "/home/viniciusbr/.local/lib/python3.6/site-packages/md2pdf/core.py", line 38, in md2pdf
    raw_html = markdown_path(md_file_path, extras=extras)
  File "/home/viniciusbr/.local/lib/python3.6/site-packages/markdown2.py", line 167, in markdown_path
    fp = codecs.open(path, 'r', encoding)
  File "/usr/lib/python3.6/codecs.py", line 897, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: 'Prática_de_Ensino_de_Biologia_-_Myriam_Krasilchik._4_Ed..md'

**Comment by ViniciusBRodrigues** [comment]
AWESOME!

Many thanks. Great job.

**Comment by ritiek** [comment]
Glad it worked for you. I'll close this then.
