### ISSUE TITLE
Support for downloading audiobooks

### ISSUE THREAD

**Issue by B0rlaug** [ritiek/scribd-downloader#38]
Please add support for downloading audiobooks, if you need a premium account please email me, thanks.

**Comment by ritiek** [comment]
I didn't knew Scribd also supports audiobooks. I'll take a look soon. Thanks for letting me know!

**Comment by ritiek** [comment]
I took a small look behind the scenes. It seems Scribd uses https://findawayworld.com for accessing audiobooks. I was able to monitor network requests through my browser and I am able to access preview mp3 of the audiobook.

For example:

The contents of this audiobook
https://www.scribd.com/audiobook/237891365/The-Lean-Startup-How-Today-s-Entrepreneurs-Use-Continuous-Innovation-to-Create-Radically-Successful-Businesses
are fetched from
https://samples.findawayworld.com/49528/49528_sample.mp3

At the moment I have no idea where this findawayworld.com URL came from. I just noticed it being requested by my browser but couldn't find any clue yet as to why this very specific URL.

**Comment by B0rlaug** [comment]
With a premium scribd account try to monitor a complete audiobook that's already available like [https://www.scribd.com/audiobook/361609535/Man-s-Search-For-Meaning](url) by using the **"Start Listening"** option.

[https://www.scribd.com/audiobook/237891365/The-Lean-Startup-How-Today-s-Entrepreneurs-Use-Continuous-Innovation-to-Create-Radically-Successful-Businesses](url) isn't available yet (will be available on 02/12/2019) and is a preview not the complete audiobook.

For example:

[https://www.scribd.com/audiobook/361609535/Man-s-Search-For-Meaning](url) would also be sourced from [https://findawayworld.com](url) but I think the URL would be something like [https://findawayworld.com/49528/49528.mp3](url) instead of [https://samples.findawayworld.com/49528/49528_sample.mp3](url) since it's a complete audiobook and not a sample.

**Comment by ritiek** [comment]
@B0rlaug Then I'll need a premium account to check this out. I don't see an email listed on your profile, so perhaps if you could provide one or write an email to me.

**Comment by B0rlaug** [comment]
@ritiek please check your email, I sent a premium account

**Comment by ritiek** [comment]
Yep, I received your mail. I'll take a look if I can find anything
interesting later in the evening today. Thanks!

**Comment by ritiek** [comment]
I tried on https://www.scribd.com/audiobook/361609535/Man-s-Search-For-Meaning. I think it is possible to download audiobooks as .mp3 (atleast with a premium account).

I'll try some more things and see if I can code this up.

**Comment by B0rlaug** [comment]
Sounds great, thanks for the update. Does the complete audiobook also use findawayworld.com like the sample did?

**Comment by B0rlaug** [comment]
Try to find the URL of [https://www.scribd.com/audiobook/237590017/The-Kite-Runner](url) on api.findawayworld.com again and determine if the book is stored in chapters (16 chapters with 1st chapter being 42 minutes long) or if the complete book is stored (around 12 hours long).

Also since the URL seems to be valid indefinitely, if the complete book (12 hours) is found on api.findawayworld.com, it shouldn't be too much harder than downloading ebooks off Scribd. Thank you for your work and the update.

**Comment by B0rlaug** [comment]
Any update regarding this?

**Comment by ritiek** [comment]
@B0rlaug I've made some progress. I'll probably have the complete code by tomorrow.

> Try to find the URL of https://www.scribd.com/audiobook/237590017/The-Kite-Runner on api.findawayworld.com again and determine if the book is stored in chapters (16 chapters with 1st chapter being 42 minutes long) or if the complete book is stored (around 12 hours long).

I've noticed that audiobooks having multiple chapters have a separate .mp3 url for each chapter.

**Comment by ritiek** [comment]
See #39 for status. (I modified your cookies in the code, so they won't work. If you're eager to test it out, You need to replace the cookie values with your own cookie values for `_scribd_session` and `_scribd_expire` in the code [here](https://github.com/ritiek/scribd-downloader/pull/39/files#diff-8a989762a7658e0817e7f8d2ba343368R101))

**Comment by ritiek** [comment]
I released v1.2.0 which supports downloading audiobooks. See README for more info. I'll close this but feel free to respond here!

**Comment by B0rlaug** [comment]
Thanks for your work man, let me know if you need anything regarding this or your spotify downloader.
