### ISSUE TITLE
Add username and password based authentication

### ISSUE THREAD

**Issue by ritiek** [ritiek/scribd-downloader#40]
...instead of relying on cookies extracted from premium-account session.

**Comment by hub2git** [comment]
This would be great!!!

**Comment by hub2git** [comment]
Does your work on #50 mean that we can now access our premium books?

**Comment by ritiek** [comment]
@hub2git Yep! Just give me a little more time, I need to update the README and fix tests. Once that is done we could merge it into master and publish a release on PyPI.

**Comment by hub2git** [comment]
Ah, thanks. Sorry to have bothered you. Just so excited. Please carry on with the amazing work you're doing. Will (try to) wait patiently. :smiley_cat:

**Comment by ritiek** [comment]
I've just released v.1.3.0 on PyPI which allows reading Scribd account credentials via a text file. Update using:
```
$ pip3 install scribd-downloader -U
```
See https://github.com/ritiek/scribd-downloader#downloading-complete-textual-books-and-audiobooks for more information.
