### ISSUE TITLE
Image Download was Corrupt

### ISSUE THREAD

**Issue by masbog** [ritiek/scribd-downloader#5]
Hi,

i just try on mac with command -i (download as image) but.... 

It may be damaged or use a file format that Preview doesn’t recognize. :(

thanks

**Comment by ritiek** [comment]
Is it possible for you to share the scribd link here?

**Comment by masbog** [comment]
@ritiek here the link https://www.scribd.com/document/274661946/soal-cpns-2015-B-1

**Comment by ritiek** [comment]
You need to specify the `-i` option depending on whether the document contains images or not. In your case, the document contains selectable text. So, you should not specify the `-i` option.

Use of `-i` actually depends on the type of document you're trying to download (textual in your case) and not the way you want to download.

I hope that clears stuff a little bit.

**Comment by masbog** [comment]
Hi @ritiek , i try without -i, but the result is untidy on txt file...

![image](https://user-images.githubusercontent.com/663374/31734798-0ce13502-b46a-11e7-8c48-89ff109f3958.png)

**Comment by ritiek** [comment]
There isn't much this tool can do. It can only download images from image documents and convert textual documents to plain (and untidy) text at the moment.

If I am able to spare some time, I might also add an option to save textual documents in .docx or a similar format where the text formatting does not mess up.

**Comment by masbog** [comment]
thank you @ritiek 👍
