### ISSUE TITLE
Convert images to PDF

### ISSUE THREAD

**Issue by pantuts** [ritiek/scribd-downloader#7]
In *nix, ImageMagick can be used to convert images to pdf but there are also other tools available. It would be really nice to automatically convert images to pdf or per user arg.

**Comment by ritiek** [comment]
I agree. This would be a nice thing to have.

**Comment by pantuts** [comment]
Thanks, can I contribute?

**Comment by ritiek** [comment]
Sure, take your time! :+1:

**Comment by pantuts** [comment]
I can't push :(

**Comment by ritiek** [comment]
Just fork this repo, push your changes and send me a pull request. :smile:

**Comment by ritiek** [comment]
Closed by 5a8ad00b35250145e41ed0c657f73d16c2a89179.
